Booking arreglo
UB-ES-2020/BikeaRent pull request #61
Opened 2020-11-15 16:03 UTC by campoos21

Tabla booking cambiada de variables para evitar errores como los de accounts

2020-11-15 17:32 UTC, realBikto requested changes
@campoos21 fes un ull als comentaris que t'he fet i, si creus que alguna cosa no et quadra, ho discutim. Igual que abans, intenta a veure que no entrin arxius del .idea o del __pycache__

2020-11-15 17:32 UTC, realBikto commented on backend/models/booking.py
> +    price = db.Column(db.Float(),nullable=False)
Aquestes tres columnes sí que han de poder ser nules, ja que quan es crea un nou rent només en tenim les dades de userid, motoid i quan ha començat.

2020-11-15 17:32 UTC, realBikto commented on backend/models/booking.py
> +    endDate = db.Column(db.String(10),nullable=False)
el tipus d'aquestes dos columnes no cal que canviin, la data s'agafa automaticament quan es fa el post.

2020-11-15 17:32 UTC, realBikto commented on backend/models/booking.py
> +    totalTimeUsed = db.Column(db.Integer,nullable=False)
aquest canvi de tipus em sembla correcte, així facilitem les coses.

2020-11-15 23:44 UTC, campoos21 commented
@realBikto done

2020-11-16 07:32 UTC, realBikto approved these changes

2020-11-16 07:39 UTC, merged